# Generated by Django 5.0.6 on 2024-05-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMDC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
