# Generated by Django 5.0.6 on 2024-05-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMDC', '0002_alter_usuarios_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Demandas',
            },
        ),
    ]
