# Generated by Django 5.0.6 on 2024-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMDC', '0003_demanda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demanda',
            old_name='height',
            new_name='ANNO',
        ),
        migrations.RenameField(
            model_name='demanda',
            old_name='weight',
            new_name='CANTIDAD_ABONADOS',
        ),
        migrations.AddField(
            model_name='demanda',
            name='EMPRESA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='ID_EMPRESA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='ID_MODALIDAD_PAGO',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='ID_TECNOLOGIA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='ID_TERMINAL',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='MES_DEL_TRIMESTRE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='MODALIDAD_PAGO',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='TECNOLOGIA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='TERMINAL',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='demanda',
            name='TRIMESTRE',
            field=models.FloatField(default=0),
        ),
    ]
