# Generated by Django 5.0.6 on 2024-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMDC', '0004_rename_height_demanda_anno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='EMPRESA',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='MODALIDAD_PAGO',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='TECNOLOGIA',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='TERMINAL',
            field=models.TextField(default=''),
        ),
    ]
