# Generated by Django 5.0.6 on 2024-05-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMDC', '0005_alter_demanda_empresa_alter_demanda_modalidad_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='ID_EMPRESA',
            field=models.TextField(default=''),
        ),
    ]
