# Generated by Django 5.0.6 on 2024-05-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMDC', '0006_alter_demanda_id_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.FloatField(default=0)),
                ('TRIMESTRE', models.FloatField(default=0)),
                ('MES_DEL_TRIMESTRE', models.FloatField(default=0)),
                ('ID_EMPRESA', models.FloatField(default=0)),
                ('EMPRESA', models.TextField(default='')),
                ('ID_SEGMENTO', models.FloatField(default=0)),
                ('SEGMENTO', models.TextField(default='')),
                ('ID_TERMINAL', models.FloatField(default=0)),
                ('TERMINAL', models.TextField(default='')),
                ('INGRESOS', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo_Trafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.FloatField(default=0)),
                ('TRIMESTRE', models.FloatField(default=0)),
                ('MES_DEL_TRIMESTRE', models.FloatField(default=0)),
                ('ID_EMPRESA', models.TextField(default='')),
                ('EMPRESA', models.TextField(default='')),
                ('ID_MODALIDAD_PAGO', models.FloatField(default=0)),
                ('MODALIDAD_PAGO', models.TextField(default='')),
                ('ID_TERMINAL', models.FloatField(default=0)),
                ('TERMINAL', models.TextField(default='')),
                ('ID_TECNOLOGIA', models.FloatField(default=0)),
                ('TECNOLOGIA', models.TextField(default='')),
                ('CANTIDAD_ABONADOS', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Demandas',
            },
        ),
        migrations.CreateModel(
            name='Demanda_Abonados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.FloatField(default=0)),
                ('TRIMESTRE', models.FloatField(default=0)),
                ('MES_DEL_TRIMESTRE', models.FloatField(default=0)),
                ('ID_EMPRESA', models.TextField(default='')),
                ('EMPRESA', models.TextField(default='')),
                ('ID_MODALIDAD_PAGO', models.FloatField(default=0)),
                ('MODALIDAD_PAGO', models.TextField(default='')),
                ('ID_TERMINAL', models.FloatField(default=0)),
                ('TERMINAL', models.TextField(default='')),
                ('ID_TECNOLOGIA', models.FloatField(default=0)),
                ('TECNOLOGIA', models.TextField(default='')),
                ('CANTIDAD_ABONADOS', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda_Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.FloatField(default=0)),
                ('TRIMESTRE', models.FloatField(default=0)),
                ('MES_DEL_TRIMESTRE', models.FloatField(default=0)),
                ('ID_EMPRESA', models.FloatField(default=0)),
                ('EMPRESA', models.TextField(default='')),
                ('ID_MODALIDAD_PAGO', models.TextField(default='')),
                ('MODALIDAD_PAGO', models.TextField(default='')),
                ('ID_TERMINAL', models.FloatField(default=0)),
                ('TERMINAL', models.TextField(default='')),
                ('CANTIDAD_INGRESOS', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda_Trafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNO', models.FloatField(default=0)),
                ('TRIMESTRE', models.FloatField(default=0)),
                ('MES_DEL_TRIMESTRE', models.FloatField(default=0)),
                ('ID_EMPRESA', models.FloatField(default=0)),
                ('EMPRESA', models.TextField(default='')),
                ('ID_MODALIDAD_PAGO', models.TextField(default='')),
                ('TRAFICO', models.FloatField(default=0)),
                ('MODALIDAD_PAGO', models.TextField(default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Demanda',
            new_name='Cargo_Suscriptores',
        ),
        migrations.AlterModelOptions(
            name='cargo_suscriptores',
            options={},
        ),
    ]
