# Generated by Django 5.0.6 on 2024-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMDC', '0007_cargo_ingresos_cargo_trafico_demanda_abonados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda_abonados',
            name='ID_MODALIDAD_PAGO',
            field=models.TextField(default=''),
        ),
    ]
