# Generated by Django 5.0.6 on 2024-05-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMDC', '0008_alter_demanda_abonados_id_modalidad_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda_abonados',
            name='ID_MODALIDAD_PAGO',
            field=models.FloatField(default=0),
        ),
    ]
