# Generated by Django 5.0.6 on 2024-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMDC', '0009_alter_demanda_abonados_id_modalidad_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo_suscriptores',
            old_name='CANTIDAD_ABONADOS',
            new_name='CANTIDAD_SUSCRIPTORES',
        ),
        migrations.RenameField(
            model_name='cargo_suscriptores',
            old_name='ID_MODALIDAD_PAGO',
            new_name='ID_SEGMENTO',
        ),
        migrations.RenameField(
            model_name='cargo_suscriptores',
            old_name='MODALIDAD_PAGO',
            new_name='SEGMENTO',
        ),
        migrations.RemoveField(
            model_name='cargo_trafico',
            name='ID_MODALIDAD_PAGO',
        ),
        migrations.RemoveField(
            model_name='cargo_trafico',
            name='ID_TECNOLOGIA',
        ),
        migrations.RemoveField(
            model_name='cargo_trafico',
            name='ID_TERMINAL',
        ),
        migrations.RemoveField(
            model_name='cargo_trafico',
            name='MODALIDAD_PAGO',
        ),
        migrations.RemoveField(
            model_name='cargo_trafico',
            name='TECNOLOGIA',
        ),
        migrations.RemoveField(
            model_name='cargo_trafico',
            name='TERMINAL',
        ),
        migrations.AlterField(
            model_name='cargo_suscriptores',
            name='ID_EMPRESA',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cargo_trafico',
            name='ID_EMPRESA',
            field=models.FloatField(default=0),
        ),
    ]
